### ISSUE TITLE
Fix search box in home

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/fgeo#37]
Search box finds stuff but the links to found stuff don't work.

**Comment by maurolepore** [comment]
Removed search box.

Was:

```
template:
  params:
    bootswatch: united
    docsearch:
      api_key: ec79b1c00aff9cd841703edc746e1a71
      index_name: fgeo
```

Now

```
template:
  params:
    bootswatch: united
```
